services:
  app:
    build:
      context: .
    command: sh -c "npx prisma db push && yarn start:prod"
    ports:
      - '3000:4000'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: redis://redis:6379
  postgres:
    image: postgres:17.5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_DB}']
      interval: 5s
      timeout: 3s
      retries: 3

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  postgres_data:
