name: Deploy to Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_DB: ${{ secrets.DATABASE_DB }}
          PORT: ${{ secrets.PORT }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << EOF
          set -e
          cd /home/ubuntu/app || exit 1
          echo "Получаем последний код..."
          git pull origin main
          echo "Очищаем старые контейнеры..."
          docker-compose down --volumes --remove-orphans || true
          docker image prune -af || true
          docker container prune -f || true
          echo "Запускаем docker-compose с переменными окружения..."
          DATABASE_USER='$DATABASE_USER' \
          DATABASE_PASSWORD='$DATABASE_PASSWORD' \
          DATABASE_DB='$DATABASE_DB' \
          DATABASE_URL='$DATABASE_URL' \
          PORT='$PORT' \
          REDIS_HOST='$REDIS_HOST' \
          REDIS_PORT='$REDIS_PORT' \
          docker-compose up -d --build
          EOF
